swagger: '2.0'
info:
  title: Money Transfer API
  description: An API for Transaction creation and Retrieve balance
  version: "1.0"
host: localhost:8080
schemes:
- http
basePath: /v1/money
produces:
- application/json
paths:
  /account/{accountNo}:
    get:
      summary: Display the account balance of specific customer account
      description: |
        Query the account balance by account number, retrieve the account balance in JSON format.
      parameters:
      - name: accountNo
        in: path
        description: account number, e.g. 477333222431
        required: true
        type: number
      responses:
        200:
          description: A JSON object of account balance
          schema:
            $ref: '#/definitions/AccountBalance'
        404:
          description: Account Number not found
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /transaction:
    post:
      summary: transfer money between 2 customer accounts
      description: |
        Create transaction for money transfer, from one account to another account
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: transaction
        in: "body"
        description: |
          Transaction details including from account No, to account No, amount, etc.
        required: true
        schema:
          $ref: "#/definitions/Transaction"
      responses:
        200:
          description: If transaction success, display a JSON object of account balance of from account
          schema:
            $ref: '#/definitions/AccountBalance'
        400:
          description: remaining balance not enough for the money transfer / Account holder name not matched / amount not positive number / currency not supported / etc.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Account Number not found
          schema:
            $ref: '#/definitions/Error'
        406:
          description: Wrong request format
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  AccountBalance:
    type: object
    properties:
      accountNo:
        type: number
        description: Account Number
        example: 477333222431
      accountName:
        type: string
        description: Account holder name
        example: "WONG SHEUNG"
      balance:
        type: number
        description: Current account balance
        example: 99999.00
      currency:
        type: string
        description: Account currency, support only HKD for API version 1
        example: HKD
      dateTime:
        type: string
        format: date-time
        description: the current timestamp of server response, in ISO-8601 date format
        example: "2018-11-08T00:00:45.606"
  Transaction:
    type: object
    properties:
      fromAccountNo:
        type: number
        description: from account number
        example: 477333222431
      toAccountNo:
        type: number
        description: to account number
        example: 987654321000
      toAccountName:
        type: string
        description: to account holder name, for double confirmation
        example: "CHEUNG SIU MING"
      amount:
        type: number
        description: amount of money to transfer
        example: 200.00
      currency:
        type: string
        description: currency of the money transaction, support only HKD for API version 1
        example: HKD
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
        description: HTTP status code of the error
        example: 404
      message:
        type: string
        description: the error description
        example: "Account Not Found [accountNo:123123]"
      dateTime:
        type: string
        format: date-time
        description: the current timestamp of server response, in ISO-8601 date format
        example: "2018-11-08T00:00:45.606"